### ISSUE TITLE
upsert example

### ISSUE THREAD

**Issue by chriswade** [felipechang/node-suitetalk#1]
Are you able to provide some insight into the fields required to make an upsert? I have managed to manipulate your example for creating a customer for upsert but am still running into issues.

This is the error I am getting
`{"$attributes":{"type":"ERROR"},"code":"USER_ERROR","message":"Please enter value(s) for: Primary Subsidiary"}`

**Comment by felipechang** [comment]
Hey @chriswade, sorry for the late response. Pretty sure that subsidiary was a required field you needed to set.
