### ISSUE TITLE
Release version 0.0.3 on npm

### ISSUE THREAD

**Issue by apeiniger** [felipechang/node-suitetalk#12]
Would it be possible to release the version 0.0.3 on npm?

**Comment by Wagan8r** [comment]
Yes, please. I also need the latest release to the handling of the account-specific domains.

**Comment by Cmacu** [comment]
Looking for update on this too.
Meanwhile: `npm i https://github.com/felipechang/node-suitetalk.git`

**Comment by alecdibble** [comment]
Plus one on this issue.

**Comment by felipechang** [comment]
Version 0.0.3 is now on NPM.
