### ISSUE TITLE
Started to get an error trying to get a customer record

### ISSUE THREAD

**Issue by chaverri** [felipechang/node-suitetalk#2]
I started to get an error saying something like 'typeId' was not found for RecordRef and checking the XSD  (https://webservices.netsuite.com/xsd/platform/v2018_1_0/core.xsd) I can see that actually that type doesn't have a typeId attribute, so I added this code to the _getAttributes method in reference.js:

```
if (!this.typeId) {
    delete attr.typeId;
}
```

But I would like you to check instead of me just sending a pull request.

Thanks.

**Comment by pacofr** [comment]
I have same issue. Solution from @chaverri worked for me too.

Thanks
