### ISSUE TITLE
Has anyone been able to create a custom record using SelectCustomFieldRef / ListOrRecordRef

### ISSUE THREAD

**Issue by arosenk35** [felipechang/node-suitetalk#30]
I cant get the record created as the value attributes are not being set .... if u have a sample please post

**Comment by l20DfX35JnKBfRn** [comment]
Hey, using this library does take some trial and error, I suggest you use the latest schema browser and debug the output XML from the SOAP API log.

Check out my fork https://github.com/l20DfX35JnKBfRn/node-suitetalk, I've merged the merge requests and added some more types which I needed for my use case. It's tested in production and working :)

Here's a snippet of some code I have, it's for setting a custom `ListOrRecordRef` field on sales order but it might help somebody in the future, including yourself:

```js
const salesOrderRecord = new Record.Types.SalesOrder();
salesOrderRecord.externalId = "PUT_ID_HERE";

// put required fields here (check examples for example) ...

const c1 = new CustomFieldRef();
c1.scriptId = name;
c1.value = new Record.Types.ListOrRecordRef();
c1.field = 'value';
c1.value.internalId = value.internalId;
c1.value.typeId = value.typeId;

salesOrderRecord.customFieldList = new Record.Lists.CustomFieldList();
salesOrderRecord.customFieldList.customFields = [c1];
service.add(salesOrderRecord);
```

@felipechang, perhaps you can transfer me as maintainer? I'm no expert but I can certainly help

**Comment by felipechang** [comment]
Hi @l20DfX35JnKBfRn, I've added you as a collaborator to the project.

**Comment by arosenk35** [comment]
thx bud .... found ur fix  couple weeks back thx!..



*Thank you*
*Anthony Rosenkrantz*

*Cell : 508-768-7465*
