### ISSUE TITLE
Publish new version to npm registry

### ISSUE THREAD

**Issue by l20DfX35JnKBfRn** [felipechang/node-suitetalk#41]
Hi @felipechang,
I think we should update node-suitetalk on npm registry, could we automate this from gitlab ci?

Perhaps triggered on tag/release creation?

Let me know if you need any assistance, I think it would be great to boost this library recognition.
Transalis ltd are using it and it's working great!

**Comment by felipechang** [comment]
Hi @l20DfX35JnKBfRn, the package is now updated on NPM. 

>could we automate this from gitlab ci

Sounds good. Though I haven't done this before, if you have instructions please forward.
