### ISSUE TITLE
"org.xml.sax.SAXException: typeId not found on {urn:core_2018_2.platform.webservices.netsuite.com}RecordRef

### ISSUE THREAD

**Issue by Usa89** [felipechang/node-suitetalk#5]
HI,

I am getting typeId not found error when trying to execute the getCustomer.js example. I was hoping I can get some help on this. Below is the response:

"root": {
            "Envelope": {
                "Body": {
                    "Fault": {
                        "faultcode": "soapenv:Server.userException",
                        "faultstring": "org.xml.sax.SAXException: typeId not found on {urn:core_2018_2.platform.webservices.netsuite.com}RecordRef",
                        "detail": {
                            "hostname": "partners011.prod.chi.netledger.com"
                        }
                    }
                }
            }
        },

**Comment by felipechang** [comment]
This was fixed in the latest merge.
