### ISSUE TITLE
How can I switch sandbox to Production?

### ISSUE THREAD

**Issue by Bayansuren** [felipechang/node-suitetalk#6]

**Comment by jared-unify** [comment]
@Bayansuren did you manage to get around this? I'm guessing you got the message Incorrect data center requested! The data center you are requesting is not the data center where your account is hosted.

**Comment by felipechang** [comment]
In order to change from SB to production just remove the _SB1 from the account parameter on the configuration object.

 account: "123456_SB1", ==>  account: "123456",
