### ISSUE TITLE
TransactionSearch basic not working with SearchEnumFilter

### ISSUE THREAD

**Issue by MUBUSHER** [felipechang/node-suitetalk#7]
Hi guys,

i am trying to use node-suitetalk and i did some changes to made transactions i have created TransactionSearchBasic and i applied transactionType filter and its not working it is adding filter/operator as attribute can you please help me how can i cleaned it up.

please have a look at request xml which is being get from service.lastRequest

Thanks in advance

![image](https://user-images.githubusercontent.com/8829789/58394422-9532ed00-805c-11e9-8d33-eeb49e6e5ab8.png)

**Comment by felipechang** [comment]
Hey @MUBUSHER, did you got this to work? Or do you have the code so I can test from my end?
