### ISSUE TITLE
how can i make loop through to get all pages on search & searchMore

### ISSUE THREAD

**Issue by MUBUSHER** [felipechang/node-suitetalk#8]
Hi,

i want to make loop through on search & searchMore to get all pages of search

`service
    .init()
    .then((/**/) => {

        // Set search preferences
        const searchPreferences = new Search.SearchPreferences();
        searchPreferences.pageSize = 100;
        service.setSearchPreferences(searchPreferences);

        // Create basic search
        const search = new Search.Basic.LocationSearchBasic();

        const nameStringField = new Search.Fields.SearchStringField();
        nameStringField.field = "name";
        nameStringField.operator = "contains";
        nameStringField.searchValue = "sweet";

        search.searchFields.push(nameStringField);

        return service.search(search);
    }).then((result, raw, soapHeader) => {

    console.log("result");
    console.log(JSON.stringify(result));

}).catch(function (err) {
    console.log("error");
    console.log(service.config.client.lastRequest);
    console.log("message");
    console.log(JSON.stringify(err));
});`

**Comment by felipechang** [comment]
Hey @MUBUSHER. When you run a basic or advanced search, the results object contains a searchId. Using this Id you can paginate using searchMoreWithId.

See:
```
service
    .init()
    .then((/**/) => {

        // Set search preferences
        const searchPreferences = new Search.SearchPreferences();
        searchPreferences.pageSize = 100;
        service.setSearchPreferences(searchPreferences);

        return service.searchMoreWithId("WEBSERVICES_1234567_12122019563679701723122702_633effee4521d", 1);
    }).then((result, raw, soapHeader) => {
    console.log(JSON.stringify(result));
}).catch(function (err) {
    console.log(JSON.stringify(err));
});
```
